language: ruby

services:
  - docker

before_install:
  - ./run build
  - ./run start detached # TODO(benjibrandt): make run build start a single command once some minor kinks are worked out

script:
  - docker ps -a
  - ping -c 3 127.0.0.1
  - ./run stop
  - ./run clean
  # TODO(benjibrandt): enable this once we have real tests - bundle exec rake test
