branch-defaults:
  eb-master-merge:
    environment: whispr-shh-benji
global:
  application_name: whispr
  branch: null
  default_ec2_keyname: whispr
  default_platform: Ruby 2.6 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
